version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password

  web_server:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - 8080:80
    restart: always
    volumes:
         -  ./:/var/www/html
    links:
      - db

volumes:
  db_data:
